### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by aleixrodri98** [sleeyax/CronetSharp#4]
Hey,

When you say to modify the cronet library, you mean to use the native way it has to import the Android local proxy when is changed? And modify that so that it works with this library? Could you specify a bit more on how would you do that?

Thanks,
Aleix

**Comment by sleeyax** [comment]
I'm not sure I understand your question. This project has nothing to do with Google's Android wrapper, it only provides native bindings and a wrapper to a given cronet binary (.dll).

In order to add HTTP proxies to cronet, you need to modify cronet's source code (which is part of chromium) and then rebuild the binary: https://chromium.googlesource.com/chromium/src/+/master/components/cronet/build_instructions.md

I'm not willing to provide further instructions on how to do this exactly because I actually spent a lot of time, effort and money to get it working myself.

**Comment by aleixrodri98** [comment]
Understood, thanks
